services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: note-taker-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NUXT_HOST=0.0.0.0
    command: npm run dev
